apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: sensu-stackdriver
spec:
  selector:
    matchLabels:
      app: sensu
  serviceName: "sensu"
  replicas: 3
  template:
    metadata:
      labels:
        app: sensu
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key
      containers:
        - name: backend
          image: sensu/sensu:5.17.1
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          command: ["/usr/local/bin/sensu-backend", "start",
          "--log-level", "debug", "--etcd-name", "$(POD_NAME)",
          "--etcd-initial-advertise-peer-urls",
          "http://$(POD_NAME).sensu.sensu-stackdriver.svc.cluster.local:2380",
          "--etcd-listen-peer-urls",
          "http://0.0.0.0:2380",
          "--etcd-listen-client-urls",
          "http://0.0.0.0:2379",
          "--etcd-advertise-client-urls",
          "http://$(POD_NAME).sensu.sensu-stackdriver.svc.cluster.local:2379",
          "--etcd-initial-cluster-token", "",
          "--etcd-initial-cluster-state", "new",
          "--etcd-initial-cluster", "backend-0=http://backend-0.sensu.sensu-stackdriver.svc.cluster.local:2380,backend-1=http://backend-1.sensu.sensu-stackdriver.svc.cluster.local:2380,backend-2=http://backend-2.sensu.sensu-stackdriver.svc.cluster.local:2380"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: STACKDRIVER_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: stackdriver
                  key: project-id
          ports:
            - protocol: TCP
              containerPort: 8080
            - protocol: TCP
              containerPort: 8081
            - protocol: TCP
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sensu
  namespace: sensu-stackdriver
spec:
  selector:
    app: sensu
  type: LoadBalancer
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ws
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: webui
      protocol: TCP
      port: 3000
      targetPort: 3000
